### ISSUE TITLE
Short version for help

### ISSUE THREAD

**Issue by renich** [at-grandpa/clim#41]
It would be really cool if you could provide `-h` as well; in addition to `--help`.

**Comment by at-grandpa** [comment]
@renich 
Thank you for your proposal!

However, if I provide "-h" by default in this library, users will not be able to use "-h" with their own options.

So I proposal that the following command informations be made available to the user.

```crystal
class MyCli < Clim
  main do
    help short: "-h" # new command informations
    run do |opts, args|
      # ...
    end
  end
end
```

How you do you feel about it?

**Comment by renich** [comment]
You're too kind! I think it's an awesome. Idea. The point is to be able to have both options if so one desires. 

Thank you for your great app and disposition.

**Comment by at-grandpa** [comment]
Thank you! Please wait until it's fixed.

**Comment by at-grandpa** [comment]
@renich
Fixed in the pull request below. Please try it.

https://github.com/at-grandpa/clim/pull/44

**Comment by renich** [comment]
Will do!

**Comment by renich** [comment]
Works great! Many thanks!
