### ISSUE TITLE
Handling and defining required args

### ISSUE THREAD

**Issue by DannyBen** [at-grandpa/clim#49]
Hi,

I am not sure if this is currently possible - I haven't seen anything in the README.

Right now, it seems like required **option flags** are handled by Clim, while required **arguments** are not.

Is there a DSL command similar to `option` to define required args? I believe that having such a command would be beneficial in two ways:

1. We can get arguments by their name, and not by their place.
2. We will not need to handle missing arguments on our own, as it will be handled by Clim.

Example to demonstrate. Consider this code:

```crystal
require "clim"

module Hello
  class Cli < Clim
    main do
      usage "hello <name>"
      
      run do |opts, args|
        if args.empty?
          puts opts.help_string
        else
          puts "hello #{args.first}"
        end
      end
    end
  end
end

Hello::Cli.start(ARGV)
```

Would be much nicer if it can be written like this:

```crystal
main do
  usage "hello <name>"
  argument "name", type: String, required: true
  
  run do |opts, args|
    # We will not be in this block unless <name> is given
    puts "hello #{args.name}" # <- using args.name instead of args.first
  end
end
```

**Comment by at-grandpa** [comment]
@DannyBen 
Thank you for a very good opinion!!
Let me think about it.

**Comment by at-grandpa** [comment]
Hi, @DannyBen .
It's now supported in the following versions!

https://github.com/at-grandpa/clim/releases/tag/v0.11.0

Thanks!
