### ISSUE TITLE
サブコマンドでの変数､メソッドの使い回し

### ISSUE THREAD

**Issue by takanotume24** [at-grandpa/clim#50]
とても初歩的な質問ですいません｡
サブコマンド同士で､処理を使いまわしたく､クラスメソッドを作成したのですがコンパイルすることができません｡
サンプルとして https://github.com/takanotume24/FakeCrystalCommand を作成しました｡
例えば``src/FakeCrystalCommand.cr``にて､それぞれのサブコマンドでクラス変数やクラスメソッドを使用する場合､どのようにすればよいのでしょうか?
https://github.com/takanotume24/FakeCrystalCommand/blob/1f21e041afb622bbf1e418f4d915a71578e8b736/src/FakeCrystalCommand.cr#L5
のようにクラス変数``@@num``,クラスメソッド``increment``を定義し､サブコマンド``"format"``内で呼びだそうとすると､コンパイル時に
```
ubuntu:~/environment/FakeCrystalCommand (master) $ crystal build src/FakeCrystalCommand.cr                                                                                                                                  
Showing last frame. Use --error-trace for full trace.

Unhandled exception: Negative argument (ArgumentError)
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
```
となりコンパイルに失敗してしまいます｡
やりたいこととしては､異なるサブコマンドで同一の処理が発生するため､その処理を関数として分けて､それを呼び出して使用した､という感じです｡crystal自体の構文の理解不足のような気もしますが､解決策をご存知でしたら教えていただけないでしょうか｡

**Comment by at-grandpa** [comment]
@takanotume24 
ライブラリを使用していただきありがとうございます！

こちらでも調査してみますね。今しばらくお待ち下さい 🙏

**Comment by at-grandpa** [comment]
@takanotume24 

こちら、macroでclassを展開しているため、`run`ブロックの中は全く別のclassの中になります。そこでclass変数が定義されていないことになるため、コンパイルエラーになっていました。

解決案としては、以下のような形でどうでしょうか？

* `module MyCommand` を定義し、その中に各runの処理を移譲する
* `module MyCommand` にクラス変数 `@@num` を定義する
* `module MyCommand` のメソッドの中で `@@num` を使用する

_FakeCrystalCommand.cr_
```crystal
require "clim"
require "./my_command"

module FakeCrystalCommand
  class Cli < Clim
    main do
      desc "Fake Crystal command."
      usage "fcrystal [sub_command] [arguments]"
      run do |opts, args|
        MyCommand.help_string(opts, args)
      end

      sub "tool" do
        desc "run a tool"
        usage "fcrystal tool [tool] [arguments]"
        run do |opts, args|
          MyCommand.tool(opts, args)
        end

        sub "format" do
          desc "format project, directories and/or files"
          usage "fcrystal tool format [options] [file or directory]"
          run do |opts, args|
            MyCommand.tool_format(opts, args)
          end
        end
      end

      sub "spec" do
        desc "build and run specs"
        usage "fcrystal spec [options] [files]"
        run do |opts, args|
          MyCommand.spec(opts, args)
        end
      end
    end
  end
end

FakeCrystalCommand::Cli.start(ARGV)
```

_my_command.cr_
```crystal
module MyCommand
  @@num = 1

  def self.increment(x : Int) : Int
    x + 1
  end

  def self.help_string(opts, arg)
    puts opts.help_string # => help string.
  end

  def self.tool(opts, arg)
    puts "Fake Crystal tool!!"
  end

  def self.tool_format(opts, arg)
    puts "Fake Crystal tool format!!"
    puts increment @@num
    puts @@num
  end

  def self.spec(opts, arg)
    puts "Fake Crystal spec!!"
  end
end
```

**Comment by takanotume24** [comment]
調査ありがとうございます!
なるほど､別クラスとして展開されているんですね｡自分もいくらか試してみて､とりあえずmoduleの外に定義すれば動くは動くと気がついたのですが､それぞれのスコープが広くなってしまって気になっていました｡ご提案していただいた方法を試してみます｡助かりました｡

**Comment by at-grandpa** [comment]
@takanotume24 
いえいえ！ご指摘ありがとうございました！
blockの記述だと「同一スコープだ」と感じてしまいがちですよね。。。 🙏 

今回のmoduleに逃がす方法は、個人的にはおすすめです。CLIのコントローラーの役割と実際の処理を分離できるのでテストしやすくなります。CLI部分が肥大化しないのもメリットの一つかなと思います。

また何かありましたらお気軽にどうぞ！
