### ISSUE TITLE
Question: How would you go about refactoring a clim app?

### ISSUE THREAD

**Issue by renich** [at-grandpa/clim#86]
I am building an application and it will have several sub-commands; with each sub-command having it's own sub-commands and so on.

I'd like to have, say:

```
src/
├── sitr
│   ├── cli
│   │   ├── business.cr
│   │   ├── nginx.cr
│   │   └── website.cr
│   ├── cli.cr
│   └── db.cr
└── sitr.cr
```

For now, `src/sitr.cr'  contains only:

```crystal
require "./sitr/*"

# TODO: Write documentation for `Sitr`
module Sitr
  NAME = "sitr"
  VER = "0.1.0"
end

Sitr::Cli.start(ARGV)
```

My problem starts in `src/sitr/cli.cr`. How can I refactor stuff that should go within `main do`? I'd like to put all the `business` sub-commands in one file and the `nginx` sub-commands in another, etc.

**Comment by at-grandpa** [comment]
Thank you for your comment. 😃
I'll try it.

**Comment by at-grandpa** [comment]
@renich 
I’m sorry for the late reply.

I wrote some sample code.
See: https://github.com/at-grandpa/refactoring-sample-code-for-clim
In this sample, a macro is used to write subcommands to other files.

Is this kind of refactoring what you intended?

**Comment by renich** [comment]
Wow! Thanks a lot @at-grandpa! Yes, it is indeed. Pretty good! 

Likewise, sorry for the late reply as well. Too much work lately. Thank you very much!

**Comment by at-grandpa** [comment]
That's good to hear!
Let’s do our best together. 👍 

I'll close this issue. ✋

**Comment by renich** [comment]
Very nice of you to say. Thank you! :smiley:
