### ISSUE TITLE
How could I split tasks in multiple files

### ISSUE THREAD

**Issue by mipmip** [at-grandpa/clim#88]
I'd like to reorganize my tasks in multiple files. Is this possible. What method would you suggest?

**Comment by at-grandpa** [comment]
@mipmip 
Thank you for your question. 😃
Would https://github.com/at-grandpa/clim/issues/86 be helpful to you?

**Comment by mipmip** [comment]
This is exactly what I'm looking for. Thanks!

**Comment by at-grandpa** [comment]
That's good to hear!
I'll close this issue. ✋
